School Result Management System/Models/Result.cs
using System;
using System.Collections.Generic;

namespace School_Result_Management_System.Models
{
    public partial class Result
    {
        public Result()
        {
            Marks = new HashSet<Mark>();
        }

        public int Id { get; set; }
        public int ClassId { get; set; }
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public decimal ResultPercentage { get; set; }
        public string ResultStatus { get; set; } = null!;
        public string ResultAddedBy { get; set; } = null!;

        public virtual Class Class { get; set; } = null!;
        public virtual Student Student { get; set; } = null!;
        public virtual ICollection<Mark> Marks { get; set; }
    }
}

School Result Management System/Controllers/MarkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class MarkController : Controller
    {
        private readonly IClassRepository _classrepo;
        private readonly ISubjectRepository _subrepo;
        private readonly IMarkRepository _markrepo;
        private readonly IResultRepository _resultrepo;
        private readonly IExamRepository _examrepo;

        public MarkController(IClassRepository classrepo,IExamRepository examrepo, ISubjectRepository subrepo, IResultRepository resultrepo, IMarkRepository markrepo)
        {
            _classrepo = classrepo;
            _subrepo = subrepo;
            _markrepo = markrepo;
            _resultrepo = resultrepo;
            _examrepo = examrepo;
        }


        public async Task<IActionResult> AssignMarks(int id, int classid, int examid)
        {
            Result result = _resultrepo.ResultExists(examid, id, classid);
            List<int> subjectIds = _classrepo.GetSubjectsByClassId(classid);
            var exam = _examrepo.GetExamByClass(examid);
            ViewData["MaxMarks"] = _examrepo.GetExamById(exam.ExamId).Name.Contains("Unit Test") ? 20:100;
            if (result!=null)
            {
                int resultId = result.Id;
                List<Mark> marks = _markrepo.GetMarksList(resultId);
                MVMWrapper model = new MVMWrapper();

                if (marks.Count==0)
                {
                    foreach (int sid in subjectIds)
                    {

                        model.mvmlist.Add(new MarksViewModel
                        {
                            Subject = _subrepo.GetAllSubjects().FirstOrDefault(x => x.Id == sid),
                            Mark = 0

                        });
                    }
                    model.ResultId = resultId;
                    return View(model);
                }
                foreach (Mark mark in marks)
                {
                    model.mvmlist.Add(new MarksViewModel
                    {
                        Subject = _subrepo.GetAllSubjects().FirstOrDefault(x => x.Id == mark.SubjectId),
                        Mark = mark.Marks

                    });
                }
                model.ResultId=resultId;
                return View(model);

            }

            else
            {
                Result res = await _resultrepo.AddResultAsync(new Result()
                {
                    ClassId = classid,
                    ExamId = examid,
                    StudentId = id
                });

               MVMWrapper model = new MVMWrapper()
                {
                    ResultId = res.Id
                };
                foreach (int sid in subjectIds)
                {

                    model.mvmlist.Add(new MarksViewModel
                    {
                        Subject = _subrepo.GetAllSubjects().FirstOrDefault(x => x.Id == sid),
                        Mark = 0

                    });
                }
                return View(model);
            }
            
         }


        [HttpPost]
        public IActionResult AssignMarks(MVMWrapper model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Mark> OldMarks = _markrepo.GetMarksList(model.ResultId);
                    List<Mark> NewMarks = new List<Mark>();
                    if (OldMarks.Any())
                    {
                        _markrepo.DeleteMarks(OldMarks);
                    }
                    foreach (MarksViewModel mvm in model.mvmlist)
                    {
                        NewMarks.Add(new Mark()
                        {
                            ResultId = model.ResultId,
                            SubjectId = mvm.Subject.Id,
                            Marks = mvm.Mark
                        });
                    }
                    _markrepo.AddMarks(NewMarks);
                   
                    ViewBag.Success = "Marks has been added successfully";
                }
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Marks Couldn't be updated";
            }


            return View(model);
        }
    }
}

School Result Management System/Controllers/ResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class ResultController : Controller
    {
        private readonly IClassRepository _classrepo;
        private readonly IExamRepository _examrepo;
        private readonly IStudentRepository _sturepo;
        private readonly ISubjectRepository _subrepo;
        private readonly IResultRepository _resultrepo;

        public ResultController(IClassRepository classrepo, IExamRepository examrepo, IStudentRepository studentrepo,ISubjectRepository subrepo,IResultRepository resultrepo)
        {
            _classrepo = classrepo;
            _examrepo = examrepo;
            _sturepo = studentrepo; 
            _subrepo = subrepo;
            _resultrepo = resultrepo;   
        }


        public void DropdownMenu()
        {
            
            ViewBag.Exams = new SelectList(_examrepo.GetAllExams(), "Id", "Name");

      
            ViewBag.Class = new SelectList(_classrepo.GetAllClasses(), "Id", "ClassName");

        }

        public IActionResult Create()
        {


            DropdownMenu();

            return View();




        }

        [HttpPost]
        public IActionResult Create(ExamViewModel model)
        {

            DropdownMenu();


            List<ExamClassRelation> registeredExams = _examrepo.GetAllExamDetails().ToList();

            var Exam = registeredExams.Find(x => x.ExamId == model.Examid && x.ClassID == model.ClassID && x.ExamYear == model.ExamYear);
            TempData["ClassId"] = model.ClassID;
           
            if (Exam != null) {
                TempData["ExamId"] = Exam.Id;
                return RedirectToAction("StudentByclass");
            }
               
            ModelState.AddModelError(" ", "The exam is not registered yet. please add the exam first");
            return View(model);




        }

        public ViewResult StudentByClass()
        {
            List<Student> students = _sturepo.GetAllStudents().Where(x => x.ClassId == Convert.ToInt32(TempData.Peek("ClassId"))).ToList();
            ResultWrapper rw = new ResultWrapper
            {
               StudentList=students,
               ClassId= Convert.ToInt32(TempData.Peek("ClassId")),
               ExamId= Convert.ToInt32(TempData["ExamId"])

            };
          
            return View(rw);
        }

      


    }
}

School Result Management System/Views/Result/Create.cshtml
@model ExamViewModel
@{
    ViewBag.Title = "Declare Result";
}


 <form accept-charset="UTF-8" role="form" method="post">
     <fieldset>

                 <div class="form-group">
                      <label>Choose Exam </label>
                       <select asp-for="Examid" class="form-control justify-content-center" asp-items="ViewBag.Exams"></select>
                      <span asp-validation-for="Examid" class="text-danger"></span>
                   </div>

                <div class="form-group">
                <label asp-for="ClassID">Choose Class</label><br />
                 <select asp-for="ClassID" class="form-control justify-content-center" asp-items="ViewBag.Class"></select>
                </div>


                  <div class="form-group">
                  <label asp-for="ExamYear">Exam Year</label>
                    <input type="text" class="form-control" asp-for="ExamYear" placeholder="eg:2078" />
                   <span asp-validation-for="ExamYear" class="text-danger"></span>
                     </div>    
                
                      <button type="submit" class="btn  btn-success ">Search</button>
                     
                      <div asp-validation-summary="All" class="text-danger" ></div>
   </fieldset>


   </form>

School Result Management System/Views/Result/StudentByClass.cshtml
@model ResultWrapper
@{

    ViewBag.Title = "Students";
}

@if (Model.StudentList.Any())
{


    <table class="table">
        <thead>
            <tr>

                <th>Student Name</th>
                <th>Roll No</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
            @foreach (Student student in Model.StudentList)
            {
                <tr>
                    <td>@student.StudentName</td>
                    <td>@student.StudentRollNo</td>

                    <td><a asp-controller="Mark" asp-action="AssignMarks" asp-route-id="@student.Id" asp-route-classid="@Model.ClassId" asp-route-examid="@Model.ExamId">Add Results</a></td>
                </tr>
            }
        </tbody>
    </table>

}
else
{

    <div class="card mb-5">
        <div class="card-body text-danger">No Students in class.</div>
    </div>
   
}