School Result Management System/Controllers/ClassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class ClassController : Controller
    {
        private IClassRepository _classrepo;


        public ClassController(IClassRepository classrepo)
        {
            _classrepo = classrepo;
        }
        public IActionResult Index()
        {
            IEnumerable<Class> classes = _classrepo.GetAllClasses();
            return View(classes);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new ClassViewModel());

        }
        [HttpPost]
        public async Task<IActionResult> Create(ClassViewModel model)
        {

            if (ModelState.IsValid)
            {
                if (_classrepo.ClassExists(model.ClassName))
                {
                    ModelState.AddModelError(string.Empty, "Class with the given classname already exists.");
                    return View(model);
                }

                Class newclass = new Class()
                {
                    ClassName = model.ClassName
                };

                await _classrepo.AddClassAsync(newclass);
                return RedirectToAction("Index");
            };
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            Class cl = _classrepo.GetClassById(id);
            return View(cl);

        }

        [HttpPost]
        public IActionResult Edit(Class cl)
        {
            if (ModelState.IsValid)
            {
                _classrepo.UpdateClass(cl);
                return RedirectToAction("Index");
            }

            return View(cl);


        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _classrepo.RemoveClassAsync(id);
                return Redirect("/Class");
            }
            catch (Exception ex)
            {
                Class cls = _classrepo.GetClassById(id);
                ViewBag.ErrorMessage = $"{cls.ClassName} class has been assigned to the students." +
                    $"Please make sure the class hasn't been assigned to any students before deleting it."
                    + $"If you want to delete the class, delete the students to which this class has been assigned and try again";
                return View("Error");
            }

        }





    }
}

School Result Management System/Controllers/ClassSubjectController.cs
using Microsoft.AspNetCore.Mvc;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class ClassSubjectController : Controller
    {
        private readonly ISubjectRepository _subrepo;
        private readonly IClassRepository _classrepo;

        public ClassSubjectController(ISubjectRepository subrepo,IClassRepository classrepo)
        {
            _subrepo = subrepo;
            _classrepo=classrepo;
        }
        public IActionResult Create(int id)
        {

            ClassSubjectViewModel model = new ClassSubjectViewModel()
            {
                SubjectIds = _classrepo.GetSubjectsByClassId(id),
                ClassSubjects = _subrepo.GetAllSubjects().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ClassSubjectViewModel model,int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _classrepo.AddSubjectsToClassAsync(model.SubjectIds, id);

                }
                model.ClassSubjects = _subrepo.GetAllSubjects().ToList();
             
                ViewBag.Success = "Subjects have been updated to the class sucessfully.";
              
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Failed to update the subjects in the class";
            }

            return View(model);


        }
    }
}

School Result Management System/Views/Class/Create.cshtml
@model ClassViewModel
@{
    ViewBag.Title = "Create Class";
}





<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Create Class</h3>
                </div>
                <div class="panel-body">
                    <form accept-charset="UTF-8" role="form" method="post">

                        <fieldset>
                            <div class="form-group">

                                <label asp-for="ClassName"></label>
                                <input asp-for="ClassName" class="form-control" placeholder="Class Name" />
                                <span asp-validation-for="ClassName" class="text-danger"></span>

                                <div asp-validation-summary="All" class="text-danger"> </div>
                                


                            </div>



                            <button type="submit" class="btn btn-lg btn-success btn-block">Create</button>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

School Result Management System/Views/Class/Edit.cshtml
@model Class
@{
    ViewBag.Title = "Edit Class";
}



<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Edit Class</h3>
                </div>
                <div class="panel-body">
                    <form accept-charset="UTF-8" role="form" method="post">

                        <fieldset>
                          <div asp-for="Id" hidden></div>
                            <div class="form-group">

                                <label asp-for="ClassName"></label>
                                <input asp-for="ClassName" class="form-control"  value=@Model.ClassName/>
                                <span asp-validation-for="ClassName" class="text-danger"></span>
                                
                            </div>
                           
                                
                         
                             <button type="submit" class="btn btn-success" style="margin-right:3%">Update</button>
                             <a asp-action="Index" class="btn  btn-danger">Cancel</a>
                           
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

School Result Management System/Views/Class/Index.cshtml
@model IEnumerable<Class>
@{
    ViewBag.Title = "Classes";
}

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<style>
   .actions{
       padding:4px;
       font-size:14px;
   }
   .delete{
       color:red;
   }
   .edit{
       color:yellowgreen;
   }
</style>



@if (Model.Any())
{
   

   <div class="card-body p-0">
        <a type="button" class="btn btn-info add-new mb-5" asp-action="Create"><i class="fa fa-plus"></i> Add New Class</a>
  <table class="table">     
<thead>
<tr>

<th>ClassName</th>
<th>Actions</th>

</tr>
</thead>
<tbody>
@foreach(Class cl in Model)
                    {
                         <tr>
                        <td>@cl.ClassName</td>
                       
                        <td>
                           
                            <a class="edit actions" asp-action="Edit" asp-route-id="@cl.Id"><i class="material-icons">&#xE254;</i>Edit</a>
                            <a class="delete actions" asp-action="Delete" onclick="return confirm('Are you sure you want to delete this item?')" asp-route-id="@cl.Id"><i class="material-icons">&#xE872;</i>Delete</a>
                            <a  class="actions" asp-controller="ClassSubject" asp-action="Create" asp-route-id="@cl.Id">Manage Subjects</a>
                        </td>
                    </tr>
                    }
</tbody>
</table>
</div>
}
else
{
    
  <div class="card mb-5">
      <div class="card-body text-danger">No Classes Created yet.</div>
      </div>
   <a type="button" class="btn btn-info add-new" asp-action="Create"><i class="fa fa-plus"></i> Add New Class</a>

}