School Result Management System/Controllers/ClassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class ClassController : Controller
    {
        private IClassRepository _classrepo;


        public ClassController(IClassRepository classrepo)
        {
            _classrepo = classrepo;
        }
        public IActionResult Index()
        {
            IEnumerable<Class> classes = _classrepo.GetAllClasses();
            return View(classes);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new ClassViewModel());

        }
        [HttpPost]
        public async Task<IActionResult> Create(ClassViewModel model)
        {

            if (ModelState.IsValid)
            {
                if (_classrepo.ClassExists(model.ClassName))
                {
                    ModelState.AddModelError(string.Empty, "Class with the given classname already exists.");
                    return View(model);
                }

                Class newclass = new Class()
                {
                    ClassName = model.ClassName
                };

                await _classrepo.AddClassAsync(newclass);
                return RedirectToAction("Index");
            };
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            Class cl = _classrepo.GetClassById(id);
            return View(cl);

        }

        [HttpPost]
        public IActionResult Edit(Class cl)
        {
            if (ModelState.IsValid)
            {
                _classrepo.UpdateClass(cl);
                return RedirectToAction("Index");
            }

            return View(cl);


        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _classrepo.RemoveClassAsync(id);
                return Redirect("/Class");
            }
            catch (Exception ex)
            {
                Class cls = _classrepo.GetClassById(id);
                ViewBag.ErrorMessage = $"{cls.ClassName} class has been assigned to the students." +
                    $"Please make sure the class hasn't been assigned to any students before deleting it."
                    + $"If you want to delete the class, delete the students to which this class has been assigned and try again";
                return View("Error");
            }

        }





    }
}

School Result Management System/Controllers/ExamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class ExamController : Controller
    {
        private readonly IClassRepository _classrepo;
        private readonly IExamRepository _examrepo;

        public ExamController(IClassRepository classrepo, IExamRepository examrepo)
        {
            _classrepo = classrepo;
            _examrepo = examrepo;

        }


        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<Exam> examsList = _examrepo.GetAllExams();
            ViewBag.Exams = new SelectList(examsList, "Id", "Name");

            IEnumerable<Class> classList = _classrepo.GetAllClasses();
            ViewBag.Class = new SelectList(classList, "Id", "ClassName");


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ExamViewModel examViewModel)
        {
            IEnumerable<Exam> examsList = _examrepo.GetAllExams();
            ViewBag.Exams = new SelectList(examsList, "Id", "Name");

            IEnumerable<Class> classList = _classrepo.GetAllClasses();
            ViewBag.Class = new SelectList(classList, "Id", "ClassName");


            if (ModelState.IsValid)
            {
                try
                {
                    ExamClassRelation exam = new ExamClassRelation()
                    {
                        ClassID = examViewModel.ClassID,
                        ExamId = examViewModel.Examid,
                        ExamYear = examViewModel.ExamYear,

                    };
                    if (_examrepo.ExamExists(exam))
                    {
                        ModelState.AddModelError("", "Exam already registered.");
                        return View(examViewModel);
                    }
                    await _examrepo.AddExamAsync(exam);
                    ViewBag.Success = "Exam Successfully added";
                }

                catch (Exception ex)
                {
                    ViewBag.Error = "Failed to add exam";
                }
            }
            return View(examViewModel);
        }

        public IActionResult Index()
        {
            var registeredExams=_examrepo.GetAllExamDetails();
            return View();
        }


    }
}

School Result Management System/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SRMSRepositories.IRepositories;
using SRMSViewModel;
using System.Security.Claims;

namespace School_Result_Management_System.Controllers
{
   
    public class LoginController : Controller
    {
        private readonly IUserRepository _userrepo;
        public LoginController(IUserRepository userrepo)
        {
            _userrepo = userrepo;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View(new UserViewModel());
            }
            return Redirect("/Home/Index");

        }

        [HttpPost]
        public async  Task<IActionResult> Index(UserViewModel model)
        {

            if (ModelState.IsValid)
            {
                var user = _userrepo.CheckUser(model.UserName, model.Password);

                if (user!=null)
                {
                    var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                    identity.AddClaim(new Claim(ClaimTypes.Name, model.UserName));

                    var principle = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync( CookieAuthenticationDefaults.AuthenticationScheme, principle,new AuthenticationProperties
                 {
                     IsPersistent = model.RememberMe
                 });

                    return RedirectToAction("Index", "Home");
                }
               
                ModelState.AddModelError(" ", "invalid username and password");
                return View(model);

            }

            return View(model);


        }

        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }
    }
}

School Result Management System/Controllers/ResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SRMSDataAccess.Models;
using SRMSRepositories.IRepositories;
using SRMSViewModel;

namespace School_Result_Management_System.Controllers
{
    [Authorize]
    public class ResultController : Controller
    {
        private readonly IClassRepository _classrepo;
        private readonly IExamRepository _examrepo;
        private readonly IStudentRepository _sturepo;
        private readonly ISubjectRepository _subrepo;
        private readonly IResultRepository _resultrepo;

        public ResultController(IClassRepository classrepo, IExamRepository examrepo, IStudentRepository studentrepo,ISubjectRepository subrepo,IResultRepository resultrepo)
        {
            _classrepo = classrepo;
            _examrepo = examrepo;
            _sturepo = studentrepo; 
            _subrepo = subrepo;
            _resultrepo = resultrepo;   
        }


        public void DropdownMenu()
        {
            
            ViewBag.Exams = new SelectList(_examrepo.GetAllExams(), "Id", "Name");

      
            ViewBag.Class = new SelectList(_classrepo.GetAllClasses(), "Id", "ClassName");

        }

        public IActionResult Create()
        {


            DropdownMenu();

            return View();




        }

        [HttpPost]
        public IActionResult Create(ExamViewModel model)
        {

            DropdownMenu();


            List<ExamClassRelation> registeredExams = _examrepo.GetAllExamDetails().ToList();

            var Exam = registeredExams.Find(x => x.ExamId == model.Examid && x.ClassID == model.ClassID && x.ExamYear == model.ExamYear);
            TempData["ClassId"] = model.ClassID;
           
            if (Exam != null) {
                TempData["ExamId"] = Exam.Id;
                return RedirectToAction("StudentByclass");
            }
               
            ModelState.AddModelError(" ", "The exam is not registered yet. please add the exam first");
            return View(model);




        }

        public ViewResult StudentByClass()
        {
            List<Student> students = _sturepo.GetAllStudents().Where(x => x.ClassId == Convert.ToInt32(TempData.Peek("ClassId"))).ToList();
            ResultWrapper rw = new ResultWrapper
            {
               StudentList=students,
               ClassId= Convert.ToInt32(TempData.Peek("ClassId")),
               ExamId= Convert.ToInt32(TempData["ExamId"])

            };
          
            return View(rw);
        }

      


    }
}

School Result Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">

</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                @*<li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                    <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                    <form class="form-inline">
                    <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                    </button>
                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                    </button>
                    </div>
                    </div>
                    </form>
                    </div>
                    </li>*@

                
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="../../index3.html" class="brand-link">
                <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Admin Dashboard</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="../../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>


                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a asp-controller="Home" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                   
                                </p>
                            </a>

                        </li>


                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Student Classes
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Class" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Create Class</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Class" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Manage Classes</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Subjects
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Subject" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Create Subject</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Subject" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Manage Subjects</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Students
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Student" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Add Student</p>
                                    </a>

                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Student" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Manage Students</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                                               <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Exams
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Exam" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Add Exam</p>
                                    </a>

                                </li>
                               <li class="nav-item">
                                     <li class="nav-item">
                                    <a asp-controller="Exam" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Registered Exams</p>
                                    </a>

                                </li>

                            

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Results
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Result" asp-action="Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Add Result</p>
                                    </a>
                                </li>
                         
                            </ul>
                        </li>

                    </ul>
                    <ul class="nav  nav-sidebar flex-column">
                         <li class="nav-item">
                                    <a asp-controller="Login" asp-action="LogOut" class="nav-link">
                                <i class="nav-icon  fas fa-solid fa-right-from-bracket"></i>
                                <p>
                                    Log Out
                                   
                                      
                                </p>
                            </a>
                            </li>
                    </ul>
                   
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card m-5">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>